
resource.AddFile("sound/battleroyale/knife.wav")
resource.AddFile("sound/battleroyale/armor.wav")
resource.AddFile("sound/battleroyale/headshot.wav")
resource.AddFile("sound/battleroyale/loot.wav")
resource.AddFile("sound/battleroyale/plane_close.wav")
resource.AddFile("sound/battleroyale/plane_far.wav")

resource.AddFile("sound/battleroyale/bullets/snap_01.wav")
resource.AddFile("sound/battleroyale/bullets/snap_02.wav")
resource.AddFile("sound/battleroyale/bullets/snap_03.wav")

resource.AddFile("sound/battleroyale/explosion/near.wav")
resource.AddFile("sound/battleroyale/explosion/far.wav")

resource.AddFile("sound/battleroyale/player/headshot.wav")

resource.AddFile("sound/battleroyale/weapons/ak47.wav")
resource.AddFile("sound/battleroyale/weapons/ak47_dist.wav")
resource.AddFile("sound/battleroyale/weapons/deagle.wav")
resource.AddFile("sound/battleroyale/weapons/deagle_dist.wav")
resource.AddFile("sound/battleroyale/weapons/flaregun.wav")
resource.AddFile("sound/battleroyale/weapons/flaregun_dist.wav")
resource.AddFile("sound/battleroyale/weapons/glock.wav")
resource.AddFile("sound/battleroyale/weapons/glock_dist.wav")
resource.AddFile("sound/battleroyale/weapons/m4a1.wav")
resource.AddFile("sound/battleroyale/weapons/m4a1_dist.wav")
resource.AddFile("sound/battleroyale/weapons/m249.wav")
resource.AddFile("sound/battleroyale/weapons/m249_dist.wav")
resource.AddFile("sound/battleroyale/weapons/mp5.wav")
resource.AddFile("sound/battleroyale/weapons/mp5_dist.wav")
resource.AddFile("sound/battleroyale/weapons/pistol.wav")
resource.AddFile("sound/battleroyale/weapons/pistol_dist.wav")
resource.AddFile("sound/battleroyale/weapons/shotgun.wav")
resource.AddFile("sound/battleroyale/weapons/shotgun_dist.wav")
resource.AddFile("sound/battleroyale/weapons/sniper.wav")
resource.AddFile("sound/battleroyale/weapons/sniper_dist.wav")
